name: Lint Dockerfile

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Debian Image
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "debian/Dockerfile"
          ignore: DL3005
          ignore: DL3008
          ignore: DL3013
          ignore: DL3015

